In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/sample_data/telco_churn.csv')

In [5]:
# Displays first 5 rows
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [6]:
# Create DF from dictionary
tempdict = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
dictdf = pd.DataFrame.from_dict(tempdict)

In [7]:
dictdf.head()

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

In [10]:
# Displays all columns
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [11]:
# Displays all data types
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [17]:
# Gives us summary statistics
# By default, the method only describes ints and floats
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3323.000000,3323.000000,3315.000000,3324.000000,3325.000000,3333.000000,3333.000000,3332.000000,3333.000000,3333.000000,3333.000000,3328.000000,3328.000000
mean,101.064806,437.182418,8.099010,179.787150,100.456214,30.557831,201.033935,100.110677,17.083540,200.872037,100.115246,9.039325,10.237294,4.479448,2.764588,1.563101
std,39.822106,42.371290,13.688365,54.419625,20.057356,9.255987,50.676652,19.932115,4.310668,50.573847,19.566710,2.275873,2.791840,2.461214,0.754086,1.315870
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.420000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.500000,114.000000,36.780000,235.325000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [18]:
# The include parameter specifies metrics to include
df.describe(include='object')

       State International plan Voice mail plan  Churn
count   3333               3333            3333   3325
unique    51                  2               2      2
top       WV                 No              No  False
freq     106               3010            2411   2842

In [20]:
# To fetch column data
df['International plan']

0        No
1        No
2        No
3       Yes
4       Yes
       ...
3328     No
3329     No
3330     No
3331    Yes
3332     No
Name: International plan, Length: 3333, dtype: object

In [22]:
# Get Data with Conditions
df[df['International plan'] == 'No']

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,SC,79,415,No,No,0,134.7,98.0,22.90,189.7,68.0,16.12,221.4,128.0,9.96,11.8,5,3.19,2.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [25]:
df[(df['International plan'] == 'No') & (df['Churn'] == False)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,SC,79,415,No,No,0,134.7,98.0,22.90,189.7,68.0,16.12,221.4,128.0,9.96,11.8,5,3.19,2.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [27]:
# Indexing with iloc
# iloc allows us to index with integers
df.iloc[15]

State                        NY
Account length              161
Area code                   415
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         317.8
Total eve calls            97.0
Total eve charge          27.01
Total night minutes       160.6
Total night calls         128.0
Total night charge         7.23
Total intl minutes          5.4
Total intl calls              9
Total intl charge          1.46
Customer service calls      4.0
Churn                      True
Name: 15, dtype: object

In [30]:
# Row, Column
df.iloc[14, 2]

415

In [31]:
df.iloc[14, 2:5]

Area code             415
International plan     No
Voice mail plan        No
Name: 14, dtype: object

In [32]:
# We can also make other attributes as indexes
state = df.copy()
state.set_index('State', inplace=True)
state.head()

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [34]:
# UPDATE VALUES
# Dropping rows
# Gets all rows that have missing values
df.isnull().sum()

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [35]:
# Drop all rows that have missing values
df.dropna(inplace=True)

In [36]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [37]:
df.drop('Area code', axis = 1) # 1 = cols, 0 = rows

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False